version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER

    networks:
      - ktm_network
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '$DB_PORT:5432'

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4:7.0
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: daniel@email.com
      PGADMIN_DEFAULT_PASSWORD: P@ssword1234
    networks:
      - ktm_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '8080:80'

  # ktmcore:
  #   image: ktmcore:1.0.0
  #   env_file:
  #     - .env
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - ktm_network

networks:
  ktm_network:
    driver: bridge
volumes:
  db-data:
  pgadmin-data:
